### ISSUE TITLE
globpath vim 7.4 compatibility

### ISSUE THREAD

**Issue by vogre** [rhysd/rust-doc.vim#1]
Using Vim 7.4 (7.4.52) I'm getting an error on :RustDoc rand (or any input)

Error detected while processing function rust_doc#open..<SNR>91_open_doc..rust_d
oc#get_modules..<SNR>91_globpath:
line    1:
E118: Too many arguments for function: globpath
E15: Invalid expression: globpath(a:dir, a:pattern, 1, 1)

Vim docs for this version also show that globpath has only three arguments.

Changing line 121 in autoload/rust_doc.vim to if v:version == 703 && has('patch465') so it doesn't include 704 seems to work correctly.

**Comment by rhysd** [comment]
Thank you for the report.

I investigated the problem and I noticed that the condition is wrong.  It seems that the version when 4th argument is added to `globpath()` is 7.4.279.  I'll fix the version check.
